### ISSUE TITLE
Fatal error: Uncaught exception 'RuntimeException' with message 'sh: 1: dmtxwrite: not found '

### ISSUE THREAD

**Issue by mozgbrasil** [krichprollsch/php-dmtx#3]
Hello

Good Morning

View the images that appear in the attempt to use the library

![captura de tela de 2017-04-05 11-55-22](https://cloud.githubusercontent.com/assets/17202780/24711617/d8529636-19f6-11e7-88e0-5c6cb2fbc947.png)
![captura de tela de 2017-04-05 11-55-50](https://cloud.githubusercontent.com/assets/17202780/24711616/d8503fda-19f6-11e7-91d2-1378dfb4aae4.png)
![captura de tela de 2017-04-05 11-55-55](https://cloud.githubusercontent.com/assets/17202780/24711618/d855e3d6-19f6-11e7-89b0-b559bd5f0fad.png)

**Comment by krichprollsch** [comment]
Hi, 
You need to install dtmx-utils (http://packages.ubuntu.com/trusty/utils/dmtx-utils) in order to have the commands `dmtxread` and `dmtxwrite` available on your server.

**Comment by mozgbrasil** [comment]
Thank you my friend
