### ISSUE TITLE
How to get encoded message?

### ISSUE THREAD

**Issue by olekjs** [krichprollsch/php-dmtx#6]
How to get encoded message. I found only one method, but it is private. Is this a good solution?
Method:
```
private function getMessage()
    {
        return implode(
            $this->options['message-separator'],
            $this->messages
        );
    }
```

**Comment by krichprollsch** [comment]
Hello @olekjs,
I'm not sure to understand your question :thinking: 
The `writer` encode a message into an image binary.

The usage [[1]](https://github.com/krichprollsch/php-dmtx#usage) section of the readme shows an example of the writer code usage.

You can save the image into a file using `saveAs()` or retrieve the binary data with `dump()`.
