### ISSUE TITLE
fwrite(): write of 8192 bytes failed with errno=32 Broken pipe

### ISSUE THREAD

**Issue by ufocruz** [krichprollsch/php-dmtx#8]
When I try to decode an base64 string, I receive this error:

exception: "ErrorException"
file: "C:\\xampp\\htdocs\\cmexx\\api\\vendor\\symfony\\process\\Pipes\\AbstractPipes.php"
line: 128
message: "fwrite(): write of 8192 bytes failed with errno=32 Broken pipe".

I tried to generate an image and use decodeFile, but had same error

**Comment by krichprollsch** [comment]
Hello @ufocruz,
Thank you for reporting this issue.
I'm sorry but I haven't touched this lib from a very long time...

Can you provide a bit more information about the issue please?
I mean, which version of php you use, the version of  `symfony\process` installed.

I would be also great if you can provide a sample of code reproducing the error :pray:

**Comment by krichprollsch** [comment]
hum and this lib is a php wrapper for https://github.com/dmtx/libdmtx.
The installation of https://github.com/dmtx/dmtx-utils is required.

~I just see there is now an official php extension: https://github.com/dmtx/php-dmtx
I suggest you to use this one directly.~

~I will deprecate my lib.~ 

The project seems even older than mine...

**Comment by ufocruz** [comment]
Hi KrichProllsch!
Thanks for the help!
Actually I deicide to use a google solution, of the ML kit. Becouse I need this decoding inside the app.
I didn't know their solution before. Decoding in php was an desperate solution. rsrs
https://developers.google.com/ml-kit/vision/barcode-scanning/android#java
Thanks again!
